/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.30
 * Generated at: 2013-05-23 15:15:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\" class=\"login_page\" style=\"background-color:#72863d;\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"utf-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("        <title>Stamp Trooper</title>\r\n");
      out.write("    \r\n");
      out.write("        <!-- Bootstrap framework -->\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"res/styles/default/bootstrap.min.css\" />\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"res/styles/default/bootstrap-responsive.min.css\" />\r\n");
      out.write("        <!-- theme color-->\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"res/styles/default/green.css\" />\r\n");
      out.write("        <!-- tooltip -->    \r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"res/styles/default/jquery.qtip.min.css\" />\r\n");
      out.write("        <!-- main styles -->\r\n");
      out.write("            <link rel=\"stylesheet\" href=\"res/styles/default/style.css\" />\r\n");
      out.write("    \r\n");
      out.write("        <!-- Favicon -->\r\n");
      out.write("            <link rel=\"shortcut icon\" href=\"res/styles/default/images/icon/favicon.ico\" />\r\n");
      out.write("    \r\n");
      out.write("        <link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>\r\n");
      out.write("    \r\n");
      out.write("        <!--[if lte IE 8]>\r\n");
      out.write("            <script src=\"res/js/html5.js\"></script>\r\n");
      out.write("\t\t\t<script src=\"res/js/respond.min.js\"></script>\r\n");
      out.write("        <![endif]-->\r\n");
      out.write("\t\t\r\n");
      out.write("    </head>\r\n");
      out.write("    <body style=\"background-color:#72863d\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"login_box\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"index\" method=\"post\" id=\"login_form\" style=\"background-color:#72863d;\">\r\n");
      out.write("\t\t\t\t<center><img src=\"res/styles/default/images/sans_fond_inverse.png\" /></center>\r\n");
      out.write("\t\t\t\t<div class=\"cnt_b\">\r\n");
      out.write("\t\t\t\t\t<div class=\"formRow\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-user\"></i></span><input type=\"text\" id=\"login\" name=\"login\" placeholder=\"Login\" value=\"Login\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"formRow\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-prepend\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"add-on\"><i class=\"icon-lock\"></i></span><input type=\"password\" id=\"password\" name=\"password\" placeholder=\"Mot de passe\" value=\"Mot de passe\" />\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"formRow\">\r\n");
      out.write("\t\t\t\t\t<center><button class=\"btn btn-inverse\" type=\"submit\">Connexion</button></center>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("        <script src=\"res/js/jquery.min.js\"></script>\r\n");
      out.write("        <script src=\"res/js/jquery.actual.min.js\"></script>\r\n");
      out.write("        <script src=\"res/js/jquery.validate.min.js\"></script>\r\n");
      out.write("\t\t<script src=\"res/js/bootstrap.min.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("            $(document).ready(function(){\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t//* boxes animation\r\n");
      out.write("\t\t\t\tform_wrapper = $('.login_box');\r\n");
      out.write("\t\t\t\tfunction boxHeight() {\r\n");
      out.write("\t\t\t\t\tform_wrapper.animate({ marginTop : ( - ( form_wrapper.height() / 2) - 24) },400);\t\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\tform_wrapper.css({ marginTop : ( - ( form_wrapper.height() / 2) - 24) });\r\n");
      out.write("                $('.linkform a,.link_reg a').on('click',function(e){\r\n");
      out.write("\t\t\t\t\tvar target\t= $(this).attr('href'),\r\n");
      out.write("\t\t\t\t\t\ttarget_height = $(target).actual('height');\r\n");
      out.write("\t\t\t\t\t$(form_wrapper).css({\r\n");
      out.write("\t\t\t\t\t\t'height'\t\t: form_wrapper.height()\r\n");
      out.write("\t\t\t\t\t});\t\r\n");
      out.write("\t\t\t\t\t$(form_wrapper.find('form:visible')).fadeOut(400,function(){\r\n");
      out.write("\t\t\t\t\t\tform_wrapper.stop().animate({\r\n");
      out.write("                            height\t : target_height,\r\n");
      out.write("\t\t\t\t\t\t\tmarginTop: ( - (target_height/2) - 24)\r\n");
      out.write("                        },500,function(){\r\n");
      out.write("                            $(target).fadeIn(400);\r\n");
      out.write("                            $('.links_btm .linkform').toggle();\r\n");
      out.write("\t\t\t\t\t\t\t$(form_wrapper).css({\r\n");
      out.write("\t\t\t\t\t\t\t\t'height'\t\t: ''\r\n");
      out.write("\t\t\t\t\t\t\t});\t\r\n");
      out.write("                        });\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t//* validation\r\n");
      out.write("\t\t\t\t/* $('#login_form').validate({\r\n");
      out.write("\t\t\t\t\tonkeyup: false,\r\n");
      out.write("\t\t\t\t\terrorClass: 'error',\r\n");
      out.write("\t\t\t\t\tvalidClass: 'valid',\r\n");
      out.write("\t\t\t\t\trules: {\r\n");
      out.write("\t\t\t\t\t\tusername: { required: true, minlength: 3 },\r\n");
      out.write("\t\t\t\t\t\tpassword: { required: true, minlength: 3 }\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\thighlight: function(element) {\r\n");
      out.write("\t\t\t\t\t\t$(element).closest('div').addClass(\"f_error\");\r\n");
      out.write("\t\t\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\t\t\tboxHeight()\r\n");
      out.write("\t\t\t\t\t\t}, 200)\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tunhighlight: function(element) {\r\n");
      out.write("\t\t\t\t\t\t$(element).closest('div').removeClass(\"f_error\");\r\n");
      out.write("\t\t\t\t\t\tsetTimeout(function() {\r\n");
      out.write("\t\t\t\t\t\t\tboxHeight()\r\n");
      out.write("\t\t\t\t\t\t}, 200)\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\terrorPlacement: function(error, element) {\r\n");
      out.write("\t\t\t\t\t\t$(element).closest('div').append(error);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});*/\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
